version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: fastapi_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
      - DEBUG=True
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=securepassword
      - POSTGRES_DB=fastapi_db
      - SECRET_KEY=supersecretjwtkeyforaccesstokensreplaceinproduction
      - REFRESH_SECRET_KEY=supersecretjwtkeyforrefreshtokensreplaceinproduction
      - HF_HOME=/tmp/huggingface
      - TRANSFORMERS_CACHE=/tmp/huggingface
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    volumes:
      - .:/workspace
    # Overwrite CMD to enable auto-reload during local development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


volumes:
  postgres_data:
  qdrant_data:
